name: Update Tags
on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    name: Update Tags
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
       fetch-depth: 0
    - name: Create missing tags
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "<>"
        bash update.sh
    - name: Push tags
      run: |
        git push --tags
